apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leonardo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/iusenkanov/leonardo
    argocd-image-updater.argoproj.io/leonardo.update-strategy: latest
    argocd-image-updater.argoproj.io/leonardo.helm-image-name: image
    argocd-image-updater.argoproj.io/leonardo.helm-tag-name: sentryRelease
spec:
  project: default
  source:
    repoURL: https://github.com/iusenkanov/leonardo.git
    targetRevision: HEAD
    path: charts
    helm:
      valueFiles:
        - values.yaml
      values: |
        sentryRelease: "{{ .Revision }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
