name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]  
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
        
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/leonardo:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/leonardo:latest

      - name: Notify Sentry of Release
        uses: getsentry/action-release@v1
        with:
          environment: production
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: bckg
          SENTRY_PROJECT: python
          SENTRY_RELEASE: ${{ github.sha }}