name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]  
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yq
        run: sudo snap install yq

      - name: Update release in values.yaml ✅ ← ВОТ ЭТО
        run: |
          yq e -i '.env[] |= if .name == "SENTRY_RELEASE" then .value = "myapp@${{ github.sha }}" else . end' charts/values.yaml


      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/leonardo:latest
