name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # ✅ Full Git history needed for Sentry to find commits
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # <--- Important for sentry-cli --auto

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/leonardo:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/leonardo:latest

      # ✅ Optional: Make the Sentry release steps explicit for debugging clarity
      - name: Create Sentry release
        run: |
          sentry-cli releases new ${{ github.sha }}
          sentry-cli releases set-commits ${{ github.sha }} --auto
          sentry-cli releases finalize ${{ github.sha }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: bckg
          SENTRY_PROJECT: python

      # ✅ Optional: Add deployment environment information (like "production")
      - name: Notify Sentry of deployment
        run: |
          sentry-cli releases deploys ${{ github.sha }} new -e production
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: bckg
          SENTRY_PROJECT: python
