name: Build and Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # нужно для commit и push
      packages: write      # для GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm values with current Git SHA
        run: |
          yq e -i '.revision = "${{ github.sha }}"' charts/values.yaml

      - name: Commit updated values.yaml
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add charts/values.yaml
          git commit -m "chore(ci): update revision to ${{ github.sha }}"
          git push

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/iusenkanov/leonardo:${{ github.sha }}
